### ISSUE TITLE
Possible binary compability problem on fs2-3.2.9 on Scala 2.12

### ISSUE THREAD

**Issue by hamnis** [typelevel/fs2#2939]
I was upgrading http4s-netty and found this while testing:

java.lang.NoSuchMethodError: 'fs2.Stream fs2.Stream$PartiallyAppliedFromIterator$.apply$extension(boolean, scala.collection.Iterator, int, cats.effect.kernel.Sync)'
    at org.http4s.jdkhttpclient.JdkHttpClient$.$anonfun$apply$17(JdkHttpClient.scala:229)

This works on fs2 3.2.8

**Comment by armanbilge** [comment]
Woops, thanks, I know what happened. But why didn't MiMa catch it :(
